namespace HomeKit.Resources
{
    public enum Category
    {
        None = 0,
        Other = 1,
        Bridge = 2,
        Fan = 3,
        GarageDoorOpener = 4,
        Lightbulb = 5,
        DoorLock = 6,
        Outlet = 7,
        Switch = 8,
        Thermostat = 9,
        Sensor = 10,
        AlarmSystem = 11,
        Door = 12,
        Window = 13,
        WindowCovering = 14,
        ProgrammableSwitch = 15,
        RangeExtender = 16,
        Camera = 17,
        VideoDoorBell = 18,
        AirPurifier = 19,
        Heater = 20,
        AirConditioner = 21,
        Humidifier = 22,
        Dehumidifier = 23,
        Speaker = 26,
        Sprinkler = 28,
        Faucet = 29,
        ShowerHead = 30,
        Television = 31,
        TargetController = 32,
    }
}
