namespace HomeKit.Characteristics
{
    public class AccessoryFlagsCharacteristic() : Uint32Characteristic("A6", ["pr", "ev"]);
    public class ActiveCharacteristic() : Uint8Characteristic("B0", ["pr", "pw", "ev"]);
    public class ActiveIdentifierCharacteristic() : Uint32Characteristic("E7", ["pr", "pw", "ev"]);
    public class ActiveTransitionCountCharacteristic() : Uint8Characteristic("4B", ["pr", "ev"]);
    public class AdministratorOnlyAccessCharacteristic() : BoolCharacteristic("01", ["pr", "pw", "ev"]);
    public class AirParticulateDensityCharacteristic() : FloatCharacteristic("64", ["pr", "ev"]);
    public class AirParticulateSizeCharacteristic() : Uint8Characteristic("65", ["pr", "ev"]);
    public class AirQualityCharacteristic() : Uint8Characteristic("95", ["pr", "ev"]);
    public class AudioFeedbackCharacteristic() : BoolCharacteristic("05", ["pr", "pw", "ev"]);
    public class BatteryLevelCharacteristic() : Uint8Characteristic("68", ["pr", "ev"]);
    public class BrightnessCharacteristic() : IntCharacteristic("08", ["pr", "pw", "ev"]);
    public class CarbonDioxideDetectedCharacteristic() : Uint8Characteristic("92", ["pr", "ev"]);
    public class CarbonDioxideLevelCharacteristic() : FloatCharacteristic("93", ["pr", "ev"]);
    public class CarbonDioxidePeakLevelCharacteristic() : FloatCharacteristic("94", ["pr", "ev"]);
    public class CarbonMonoxideDetectedCharacteristic() : Uint8Characteristic("69", ["pr", "ev"]);
    public class CarbonMonoxideLevelCharacteristic() : FloatCharacteristic("90", ["pr", "ev"]);
    public class CarbonMonoxidePeakLevelCharacteristic() : FloatCharacteristic("91", ["pr", "ev"]);
    public class ChargingStateCharacteristic() : Uint8Characteristic("8F", ["pr", "ev"]);
    public class ClosedCaptionsCharacteristic() : Uint8Characteristic("DD", ["pr", "pw", "ev"]);
    public class ColorTemperatureCharacteristic() : Uint32Characteristic("CE", ["pr", "pw", "ev"]);
    public class ConfiguredNameCharacteristic() : StringCharacteristic("E3", ["pr", "pw", "ev"]);
    public class ContactSensorStateCharacteristic() : Uint8Characteristic("6A", ["pr", "ev"]);
    public class CoolingThresholdTemperatureCharacteristic() : FloatCharacteristic("0D", ["pr", "pw", "ev"]);
    public class CurrentAirPurifierStateCharacteristic() : Uint8Characteristic("A9", ["pr", "ev"]);
    public class CurrentAmbientLightLevelCharacteristic() : FloatCharacteristic("6B", ["pr", "ev"]);
    public class CurrentDoorStateCharacteristic() : Uint8Characteristic("0E", ["pr", "ev"]);
    public class CurrentFanStateCharacteristic() : Uint8Characteristic("AF", ["pr", "ev"]);
    public class CurrentHeaterCoolerStateCharacteristic() : Uint8Characteristic("B1", ["pr", "ev"]);
    public class CurrentHeatingCoolingStateCharacteristic() : Uint8Characteristic("0F", ["pr", "ev"]);
    public class CurrentHorizontalTiltAngleCharacteristic() : IntCharacteristic("6C", ["pr", "ev"]);
    public class CurrentHumidifierDehumidifierStateCharacteristic() : Uint8Characteristic("B3", ["pr", "ev"]);
    public class CurrentMediaStateCharacteristic() : Uint8Characteristic("E0", ["pr", "ev"]);
    public class CurrentPositionCharacteristic() : Uint8Characteristic("6D", ["pr", "ev"]);
    public class CurrentRelativeHumidityCharacteristic() : FloatCharacteristic("10", ["pr", "ev"]);
    public class CurrentSlatStateCharacteristic() : Uint8Characteristic("AA", ["pr", "ev"]);
    public class CurrentTemperatureCharacteristic() : FloatCharacteristic("11", ["pr", "ev"]);
    public class CurrentTiltAngleCharacteristic() : IntCharacteristic("C1", ["pr", "ev"]);
    public class CurrentVerticalTiltAngleCharacteristic() : IntCharacteristic("6E", ["pr", "ev"]);
    public class CurrentVisibilityStateCharacteristic() : Uint8Characteristic("35", ["pr", "ev"]);
    public class DigitalZoomCharacteristic() : FloatCharacteristic("1D", ["pr", "pw", "ev"]);
    public class DisplayOrderCharacteristic() : Tlv8Characteristic("36", ["pr", "pw", "ev"]);
    public class FilterChangeIndicationCharacteristic() : Uint8Characteristic("AC", ["pr", "ev"]);
    public class FilterLifeLevelCharacteristic() : FloatCharacteristic("AB", ["pr", "ev"]);
    public class FirmwareRevisionCharacteristic() : StringCharacteristic("52", ["pr"]);
    public class HardwareRevisionCharacteristic() : StringCharacteristic("53", ["pr"]);
    public class HeatingThresholdTemperatureCharacteristic() : FloatCharacteristic("12", ["pr", "pw", "ev"]);
    public class HoldPositionCharacteristic() : BoolCharacteristic("6F", ["pw"]);
    public class HueCharacteristic() : FloatCharacteristic("13", ["pr", "pw", "ev"]);
    public class IdentifierCharacteristic() : Uint32Characteristic("E6", ["pr"]);
    public class IdentifyCharacteristic() : BoolCharacteristic("14", ["pw"]);
    public class ImageMirroringCharacteristic() : BoolCharacteristic("1F", ["pr", "pw", "ev"]);
    public class ImageRotationCharacteristic() : FloatCharacteristic("1E", ["pr", "pw", "ev"]);
    public class InputSourceTypeCharacteristic() : Uint8Characteristic("DB", ["pr", "ev"]);
    public class InputDeviceTypeCharacteristic() : Uint8Characteristic("DC", ["pr", "ev"]);
    public class InUseCharacteristic() : Uint8Characteristic("D2", ["pr", "ev"]);
    public class IsConfiguredCharacteristic() : Uint8Characteristic("D6", ["pr", "pw", "ev"]);
    public class LeakDetectedCharacteristic() : Uint8Characteristic("70", ["pr", "ev"]);
    public class LockControlPointCharacteristic() : Tlv8Characteristic("19", ["pw"]);
    public class LockCurrentStateCharacteristic() : Uint8Characteristic("1D", ["pr", "ev"]);
    public class LockLastKnownActionCharacteristic() : Uint8Characteristic("1C", ["pr", "ev"]);
    public class LockManagementAutoSecurityTimeoutCharacteristic() : Uint32Characteristic("1A", ["pr", "pw", "ev"]);
    public class LockPhysicalControlsCharacteristic() : Uint8Characteristic("A7", ["pr", "pw", "ev"]);
    public class LockTargetStateCharacteristic() : Uint8Characteristic("1E", ["pr", "pw", "ev"]);
    public class LogsCharacteristic() : Tlv8Characteristic("1F", ["pr", "ev"]);
    public class ManufacturerCharacteristic() : StringCharacteristic("20", ["pr"]);
    public class ModelCharacteristic() : StringCharacteristic("21", ["pr"]);
    public class MotionDetectedCharacteristic() : BoolCharacteristic("22", ["pr", "ev"]);
    public class MuteCharacteristic() : BoolCharacteristic("1A", ["pr", "pw", "ev"]);
    public class NameCharacteristic() : StringCharacteristic("23", ["pr"]);
    public class NightVisionCharacteristic() : BoolCharacteristic("1B", ["pr", "pw", "ev"]);
    public class NitrogenDioxideDensityCharacteristic() : FloatCharacteristic("C4", ["pr", "ev"]);
    public class ObstructionDetectedCharacteristic() : BoolCharacteristic("24", ["pr", "ev"]);
    public class OccupancyDetectedCharacteristic() : Uint8Characteristic("71", ["pr", "ev"]);
    public class OnCharacteristic() : BoolCharacteristic("25", ["pr", "pw", "ev"]);
    public class OpticalZoomCharacteristic() : FloatCharacteristic("1C", ["pr", "pw", "ev"]);
    public class OutletInUseCharacteristic() : BoolCharacteristic("26", ["pr", "ev"]);
    public class OzoneDensityCharacteristic() : FloatCharacteristic("C3", ["pr", "ev"]);
    public class PM10DensityCharacteristic() : FloatCharacteristic("C7", ["pr", "ev"]);
    public class PairSetupCharacteristic() : Tlv8Characteristic("4C", ["pr", "pw"]);
    public class PairVerifyCharacteristic() : Tlv8Characteristic("4E", ["pr", "pw"]);
    public class PairingFeaturesCharacteristic() : Uint8Characteristic("4F", ["pr"]);
    public class PairingPairingsCharacteristic() : Tlv8Characteristic("50", ["pr", "pw"]);
    public class PictureModeCharacteristic() : Uint8Characteristic("E2", ["pr", "pw", "ev"]);
    public class PositionStateCharacteristic() : Uint8Characteristic("72", ["pr", "ev"]);
    public class PowerModeSelectionCharacteristic() : Uint8Characteristic("DF", ["pw"]);
    public class ProgramModeCharacteristic() : Uint8Characteristic("D1", ["pr", "ev"]);
    public class ProgrammableSwitchEventCharacteristic() : Uint8Characteristic("73", ["pr", "ev"]);
    public class RelativeHumidityDehumidifierThresholdCharacteristic() : FloatCharacteristic("C9", ["pr", "pw", "ev"]);
    public class RelativeHumidityHumidifierThresholdCharacteristic() : FloatCharacteristic("CA", ["pr", "pw", "ev"]);
    public class RemainingDurationCharacteristic() : Uint32Characteristic("D4", ["pr", "ev"]);
    public class RemoteKeyCharacteristic() : Uint8Characteristic("E1", ["pw"]);
    public class ResetFilterIndicationCharacteristic() : Uint8Characteristic("AD", ["pw"]);
    public class RotationDirectionCharacteristic() : IntCharacteristic("28", ["pr", "pw", "ev"]);
    public class RotationSpeedCharacteristic() : FloatCharacteristic("29", ["pr", "pw", "ev"]);
    public class SaturationCharacteristic() : FloatCharacteristic("2F", ["pr", "pw", "ev"]);
    public class SecuritySystemAlarmTypeCharacteristic() : Uint8Characteristic("8E", ["pr", "ev"]);
    public class SecuritySystemCurrentStateCharacteristic() : Uint8Characteristic("66", ["pr", "ev"]);
    public class SecuritySystemTargetStateCharacteristic() : Uint8Characteristic("67", ["pr", "pw", "ev"]);
    public class SelectedRTPStreamConfigurationCharacteristic() : Tlv8Characteristic("17", ["pr", "pw"]);
    public class SerialNumberCharacteristic() : StringCharacteristic("30", ["pr"]);
    public class ServiceLabelIndexCharacteristic() : Uint8Characteristic("CB", ["pr"]);
    public class ServiceLabelNamespaceCharacteristic() : Uint8Characteristic("CD", ["pr"]);
    public class SetDurationCharacteristic() : Uint32Characteristic("D3", ["pr", "pw", "ev"]);
    public class SetupEndpointsCharacteristic() : Tlv8Characteristic("18", ["pr", "pw"]);
    public class SlatTypeCharacteristic() : Uint8Characteristic("C0", ["pr"]);
    public class SleepDiscoveryModeCharacteristic() : Uint8Characteristic("E8", ["pr", "ev"]);
    public class SmokeDetectedCharacteristic() : Uint8Characteristic("76", ["pr", "ev"]);
    public class StatusActiveCharacteristic() : BoolCharacteristic("75", ["pr", "ev"]);
    public class StatusFaultCharacteristic() : Uint8Characteristic("77", ["pr", "ev"]);
    public class StatusJammedCharacteristic() : Uint8Characteristic("78", ["pr", "ev"]);
    public class StatusLowBatteryCharacteristic() : Uint8Characteristic("79", ["pr", "ev"]);
    public class StatusTamperedCharacteristic() : Uint8Characteristic("7A", ["pr", "ev"]);
    public class StreamingStatusCharacteristic() : Tlv8Characteristic("20", ["pr", "ev"]);
    public class SulphurDioxideDensityCharacteristic() : FloatCharacteristic("C5", ["pr", "ev"]);
    public class SupportedAudioStreamConfigurationCharacteristic() : Tlv8Characteristic("15", ["pr"]);
    public class SupportedRTPConfigurationCharacteristic() : Tlv8Characteristic("16", ["pr"]);
    public class SupportedVideoStreamConfigurationCharacteristic() : Tlv8Characteristic("14", ["pr"]);
    public class SupportedTransitionConfigurationCharacteristic() : Tlv8Characteristic("44", ["pr"]);
    public class SwingModeCharacteristic() : Uint8Characteristic("B6", ["pr", "pw", "ev"]);
    public class TargetAirPurifierStateCharacteristic() : Uint8Characteristic("A8", ["pr", "pw", "ev"]);
    public class TargetAirQualityCharacteristic() : Uint8Characteristic("AE", ["pr", "pw", "ev"]);
    public class TargetDoorStateCharacteristic() : Uint8Characteristic("32", ["pr", "pw", "ev"]);
    public class TargetFanStateCharacteristic() : Uint8Characteristic("BF", ["pr", "pw", "ev"]);
    public class TargetHeaterCoolerStateCharacteristic() : Uint8Characteristic("B2", ["pr", "pw", "ev"]);
    public class TargetHeatingCoolingStateCharacteristic() : Uint8Characteristic("33", ["pr", "pw", "ev"]);
    public class TargetHorizontalTiltAngleCharacteristic() : IntCharacteristic("7B", ["pr", "pw", "ev"]);
    public class TargetHumidifierDehumidifierStateCharacteristic() : Uint8Characteristic("B4", ["pr", "pw", "ev"]);
    public class TargetMediaStateCharacteristic() : Uint8Characteristic("37", ["pr", "pw", "ev"]);
    public class TargetPositionCharacteristic() : Uint8Characteristic("7C", ["pr", "pw", "ev"]);
    public class TargetRelativeHumidityCharacteristic() : FloatCharacteristic("34", ["pr", "pw", "ev"]);
    public class TargetSlatStateCharacteristic() : Uint8Characteristic("BE", ["pr", "pw", "ev"]);
    public class TargetTemperatureCharacteristic() : FloatCharacteristic("35", ["pr", "pw", "ev"]);
    public class TargetTiltAngleCharacteristic() : IntCharacteristic("C2", ["pr", "pw", "ev"]);
    public class TargetVerticalTiltAngleCharacteristic() : IntCharacteristic("7D", ["pr", "pw", "ev"]);
    public class TargetVisibilityStateCharacteristic() : Uint8Characteristic("34", ["pr", "pw", "ev"]);
    public class TemperatureDisplayUnitsCharacteristic() : Uint8Characteristic("36", ["pr", "pw", "ev"]);
    public class TransitionControlCharacteristic() : Tlv8Characteristic("43", ["pr", "pw", "wr"]);
    public class VOCDensityCharacteristic() : FloatCharacteristic("C8", ["pr", "ev"]);
    public class ValveTypeCharacteristic() : Uint8Characteristic("D5", ["pr", "ev"]);
    public class VersionCharacteristic() : StringCharacteristic("37", ["pr", "ev"]);
    public class VolumeCharacteristic() : Uint8Characteristic("19", ["pr", "pw", "ev"]);
    public class VolumeControlTypeCharacteristic() : Uint8Characteristic("E9", ["pr", "ev"]);
    public class VolumeSelectorCharacteristic() : Uint8Characteristic("EA", ["pw"]);
    public class WaterLevelCharacteristic() : FloatCharacteristic("B5", ["pr", "ev"]);
}
